### ISSUE TITLE
Incorrect display of UUID 

### ISSUE THREAD

**Issue by archroot** [seyfahni/OnlineTime#17]
Incorrect display of UUID 

**System information:**
 - Server:   Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
 - Proxy:  BungeeCord BotFilter v3.8.6-dev
 - Plugin version: OnlineTime 2.0.2

![Снимок экрана_2021-05-31_20-42-31](https://user-images.githubusercontent.com/41123605/120229917-df0bca80-c256-11eb-9f64-1e8fbb0de38e.png)

**Comment by seyfahni** [comment]
This isn't a bug, I'm saving the UUID as binary for performance improvement and storage saving.
To properly display the uuid you can use:
```sql
SELECT id, HEX(uuid) AS uuid, name, time FROM `online_time`;
```
